"""Signals page — recent buy/sell decisions with reasoning."""

from __future__ import annotations

import pandas as pd
import streamlit as st

from dashboard.data import DataLoadError, load_decisions
from dashboard.fmt import fmt_date, fmt_datetime, fmt_null, render_export_button


def _render_signal_card(d: dict) -> None:
    """Render a single signal decision as a card."""
    signal = (d.get("signal") or "").upper()
    ticker = d.get("ticker", "")
    ts = fmt_datetime(d.get("timestamp"))
    payload = d.get("payload") or {}

    color = "green" if signal == "BUY" else "red" if signal == "SELL" else "gray"
    with st.container(border=True):
        st.subheader(f":{color}[{signal}]  {ticker}  —  {ts}")

        reasons = (
            payload.get("reasons_pass")
            or payload.get("reasons_fail")
            or payload.get("reasons")
            or []
        )
        if reasons:
            for r in reasons:
                st.write(f"• {r}")
        if payload.get("reasoning"):
            st.caption(payload["reasoning"])


def render() -> None:
    """Render the Signals page."""
    st.title("Signals")
    st.caption(
        "Buy and sell decisions generated by the analysis "
        "pipeline, with the reasoning behind each signal."
    )

    # Filters in sidebar
    limit = st.sidebar.slider(
        "Max signals",
        10,
        100,
        30,
        help="Number of recent decisions to display. Increase to see older signals.",
    )

    try:
        with st.spinner("Loading recent buy/sell decisions..."):
            decisions = load_decisions(limit=limit)
    except DataLoadError as exc:
        st.error(str(exc))
        return

    # Classify decisions
    buy_decisions = [d for d in decisions if (d.get("signal") or "").upper() == "BUY"]
    sell_decisions = [d for d in decisions if (d.get("signal") or "").upper() == "SELL"]
    other_decisions = [
        d for d in decisions if (d.get("signal") or "").upper() not in ("BUY", "SELL")
    ]
    latest_ts = fmt_date(decisions[0].get("timestamp")) if decisions else fmt_null(None)

    # ── Tier 1: Hero metrics ──
    col1, col2, col3, col4 = st.columns(4, gap="large", vertical_alignment="bottom")
    with col1:
        st.metric(
            "Total Signals",
            len(decisions),
            help="All decisions in the selected range, including buys, sells, and holds.",
        )
    with col2:
        st.metric(
            "Buys",
            len(buy_decisions),
            help="Stocks that passed all five pipeline stages and met margin-of-safety thresholds.",
        )
    with col3:
        st.metric(
            "Sells",
            len(sell_decisions),
            help="Positions flagged for exit — thesis "
            "invalidated or price exceeds intrinsic value.",
        )
    with col4:
        st.metric(
            "Latest Signal",
            latest_ts,
            help="Date of the most recent decision.",
        )

    with st.popover("How are signals generated?"):
        st.markdown(
            "Each candidate goes through a **5-stage "
            "pipeline**:\n\n"
            "1. **Quant screen** — Piotroski F-score, P/B, "
            "ROIC thresholds (pure math, no AI)\n"
            "2. **Moat analysis** — AI evaluates competitive "
            "advantages\n"
            "3. **Management quality** — AI assesses "
            "leadership track record\n"
            "4. **Intrinsic value** — DCF, EPV, and asset "
            "floor models\n"
            "5. **Thesis generation** — Full investment "
            "thesis\n\n"
            "A **BUY** fires only when all stages pass and "
            "margin of safety exceeds the threshold. "
            "A **SELL** fires when the original thesis is "
            "invalidated or the stock is overvalued."
        )

    st.divider()

    if not decisions:
        st.info(
            "No decisions on record for this range. "
            "Signals are generated during each analysis cycle. "
            "Try increasing the 'Max signals' slider."
        )
        return

    # Export decisions as CSV
    signal_rows = []
    for d in decisions:
        signal_rows.append(
            {
                "Signal": (d.get("signal") or "").upper(),
                "Ticker": d.get("ticker", ""),
                "Timestamp": d.get("timestamp", ""),
                "Reasoning": (d.get("payload") or {}).get("reasoning", ""),
            }
        )
    signal_df = pd.DataFrame(signal_rows)
    render_export_button(signal_df, "signals", label="Download Signals CSV")

    if "page_toast_shown" not in st.session_state:
        st.toast(
            f"Showing {len(decisions)} signals "
            f"({len(buy_decisions)} buys, "
            f"{len(sell_decisions)} sells)",
            icon="✅",
        )
        st.session_state.page_toast_shown = True

    # ── Tier 2: Primary content in tabs ──
    tab_all, tab_buys, tab_sells = st.tabs(["All Signals", "Buys", "Sells"])

    with tab_all:
        for d in decisions:
            _render_signal_card(d)

    with tab_buys:
        if buy_decisions:
            for d in buy_decisions:
                _render_signal_card(d)
        else:
            st.info(
                "No BUY signals in this range. "
                "The quant screen may not have found "
                "candidates meeting all thresholds."
            )

    with tab_sells:
        if sell_decisions:
            for d in sell_decisions:
                _render_signal_card(d)
        else:
            st.info(
                "No SELL signals in this range. "
                "Positions are held until the thesis is "
                "invalidated or the price exceeds "
                "intrinsic value."
            )

    # ── Tier 3: Supplementary content ──
    if other_decisions:
        with st.expander(f"Other Signals ({len(other_decisions)})"):
            for d in other_decisions:
                _render_signal_card(d)
