"""Signals page — recent buy/sell decisions with reasoning."""

from __future__ import annotations

from datetime import datetime, timedelta

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from dashboard.data import DataLoadError, load_decisions, load_thesis_content
from dashboard.fmt import fmt_date, fmt_datetime, fmt_null, render_export_button

PAGE_SIZE = 10


def _render_signal_card(d: dict) -> None:
    """Render a single signal decision as an expandable card with thesis."""
    signal = (d.get("signal") or "").upper()
    ticker = d.get("ticker", "")
    ts = fmt_datetime(d.get("timestamp"))
    payload = d.get("payload") or {}

    color = "green" if signal == "BUY" else "red" if signal == "SELL" else "gray"

    with st.expander(f":{color}[{signal}]  {ticker}  —  {ts}", expanded=False):
        reasons = (
            payload.get("reasons_pass")
            or payload.get("reasons_fail")
            or payload.get("reasons")
            or []
        )
        if reasons:
            for r in reasons:
                st.write(f"• {r}")
        if payload.get("reasoning"):
            st.caption(payload["reasoning"])

        st.divider()

        thesis = load_thesis_content(ticker) if ticker else None
        if thesis:
            st.markdown("**Investment Thesis**")
            st.markdown(thesis)
        else:
            st.caption("No thesis available for this ticker.")


def _render_paginated_cards(signals: list[dict], tab_name: str) -> None:
    """Render signal cards with pagination controls."""
    if not signals:
        if tab_name == "buys":
            st.info(
                "No BUY signals in this range. "
                "The quant screen may not have found "
                "candidates meeting all thresholds."
            )
        elif tab_name == "sells":
            st.info(
                "No SELL signals in this range. "
                "Positions are held until the thesis is "
                "invalidated or the price exceeds "
                "intrinsic value."
            )
        else:
            st.info("No signals match the current filters.")
        return

    page_key = f"signals_page_{tab_name}"
    if page_key not in st.session_state:
        st.session_state[page_key] = 0

    total_pages = max(1, (len(signals) + PAGE_SIZE - 1) // PAGE_SIZE)
    st.session_state[page_key] = min(st.session_state[page_key], total_pages - 1)

    start_idx = st.session_state[page_key] * PAGE_SIZE
    end_idx = start_idx + PAGE_SIZE
    page_slice = signals[start_idx:end_idx]

    for d in page_slice:
        _render_signal_card(d)

    if total_pages > 1:
        col_prev, col_info, col_next = st.columns([1, 2, 1])
        with col_prev:
            if st.button(
                "\u2190 Previous",
                disabled=st.session_state[page_key] == 0,
                key=f"prev_{tab_name}",
            ):
                st.session_state[page_key] -= 1
                st.rerun()
        with col_info:
            st.caption(f"Page {st.session_state[page_key] + 1} of {total_pages}")
        with col_next:
            if st.button(
                "Next \u2192",
                disabled=st.session_state[page_key] >= total_pages - 1,
                key=f"next_{tab_name}",
            ):
                st.session_state[page_key] += 1
                st.rerun()


def render() -> None:
    """Render the Signals page."""
    st.title("Signals")
    st.caption(
        "Buy and sell decisions generated by the analysis "
        "pipeline, with the reasoning behind each signal."
    )

    # Filters in sidebar
    limit = st.sidebar.slider(
        "Max signals",
        10,
        100,
        30,
        help="Number of recent decisions to display. Increase to see older signals.",
    )

    st.sidebar.text_input("Filter by ticker", key="signal_ticker_filter")

    today = datetime.now().date()
    default_start = today - timedelta(days=90)
    st.sidebar.date_input(
        "Date range",
        value=(default_start, today),
        key="signal_date_range",
    )

    try:
        with st.spinner("Loading recent buy/sell decisions..."):
            decisions = load_decisions(limit=limit)
    except DataLoadError as exc:
        st.error(str(exc))
        return

    # Track last-seen signal timestamp
    if decisions:
        latest_signal_ts = decisions[0].get("timestamp", "")
        last_seen = st.session_state.get("last_seen_signal_ts", "")

        if last_seen and latest_signal_ts > last_seen:
            # Count new signals since last visit
            new_count = sum(1 for d in decisions if d.get("timestamp", "") > last_seen)
            new_buys = sum(
                1
                for d in decisions
                if d.get("timestamp", "") > last_seen and (d.get("signal") or "").upper() == "BUY"
            )
            new_sells = sum(
                1
                for d in decisions
                if d.get("timestamp", "") > last_seen and (d.get("signal") or "").upper() == "SELL"
            )

            parts = []
            if new_buys:
                parts.append(f"{new_buys} BUY")
            if new_sells:
                parts.append(f"{new_sells} SELL")
            label = " and ".join(parts) if parts else f"{new_count} new"
            if "page_toast_shown" not in st.session_state:
                st.toast(
                    f"{label} signal{'s' if new_count > 1 else ''} since your last visit",
                    icon=":material/notifications:",
                )

        st.session_state.last_seen_signal_ts = latest_signal_ts

    # ── Apply filters ──
    filtered = decisions

    ticker_filter = st.session_state.get("signal_ticker_filter", "").strip().upper()
    if ticker_filter:
        filtered = [d for d in filtered if ticker_filter in d.get("ticker", "").upper()]

    date_range = st.session_state.get("signal_date_range")
    if isinstance(date_range, tuple) and len(date_range) == 2:
        start_str, end_str = str(date_range[0]), str(date_range[1])
        filtered = [d for d in filtered if start_str <= d.get("timestamp", "")[:10] <= end_str]

    # Classify decisions
    buy_decisions = [d for d in filtered if (d.get("signal") or "").upper() == "BUY"]
    sell_decisions = [d for d in filtered if (d.get("signal") or "").upper() == "SELL"]
    other_decisions = [
        d for d in filtered if (d.get("signal") or "").upper() not in ("BUY", "SELL")
    ]
    latest_ts = fmt_date(filtered[0].get("timestamp")) if filtered else fmt_null(None)

    # ── Tier 1: Hero metrics ──
    col1, col2, col3, col4 = st.columns(4, gap="large", vertical_alignment="bottom")
    with col1:
        st.metric(
            "Total Signals",
            len(filtered),
            help="All decisions in the selected range, including buys, sells, and holds.",
        )
    with col2:
        st.metric(
            "Buys",
            len(buy_decisions),
            help="Stocks that passed all five pipeline stages and met margin-of-safety thresholds.",
        )
    with col3:
        st.metric(
            "Sells",
            len(sell_decisions),
            help="Positions flagged for exit — thesis "
            "invalidated or price exceeds intrinsic value.",
        )
    with col4:
        st.metric(
            "Latest Signal",
            latest_ts,
            help="Date of the most recent decision.",
        )

    with st.popover("How are signals generated?"):
        st.markdown(
            "Each candidate goes through a **5-stage "
            "pipeline**:\n\n"
            "1. **Quant screen** — Piotroski F-score, P/B, "
            "ROIC thresholds (pure math, no AI)\n"
            "2. **Moat analysis** — AI evaluates competitive "
            "advantages\n"
            "3. **Management quality** — AI assesses "
            "leadership track record\n"
            "4. **Intrinsic value** — DCF, EPV, and asset "
            "floor models\n"
            "5. **Thesis generation** — Full investment "
            "thesis\n\n"
            "A **BUY** fires only when all stages pass and "
            "margin of safety exceeds the threshold. "
            "A **SELL** fires when the original thesis is "
            "invalidated or the stock is overvalued."
        )

    st.divider()

    st.caption(f"Showing {len(filtered)} of {len(decisions)} signals")

    if not decisions:
        st.info(
            "No decisions on record for this range. "
            "Signals are generated during each analysis cycle. "
            "Try increasing the 'Max signals' slider."
        )
        return

    # Export decisions as CSV
    signal_rows = []
    for d in decisions:
        signal_rows.append(
            {
                "Signal": (d.get("signal") or "").upper(),
                "Ticker": d.get("ticker", ""),
                "Timestamp": d.get("timestamp", ""),
                "Reasoning": (d.get("payload") or {}).get("reasoning", ""),
            }
        )
    signal_df = pd.DataFrame(signal_rows)
    render_export_button(signal_df, "signals", label="Download Signals CSV")

    if "page_toast_shown" not in st.session_state:
        st.toast(
            f"Showing {len(decisions)} signals "
            f"({len(buy_decisions)} buys, "
            f"{len(sell_decisions)} sells)",
            icon="\u2705",
        )
        st.session_state.page_toast_shown = True

    # ── Tier 2: Primary content in tabs ──
    tab_all, tab_buys, tab_sells, tab_timeline = st.tabs(
        ["All Signals", "Buys", "Sells", "Timeline"]
    )

    with tab_all:
        _render_paginated_cards(filtered, "all")

    with tab_buys:
        _render_paginated_cards(buy_decisions, "buys")

    with tab_sells:
        _render_paginated_cards(sell_decisions, "sells")

    with tab_timeline:
        if filtered:
            fig = go.Figure()

            if buy_decisions:
                fig.add_trace(
                    go.Scatter(
                        x=[d["timestamp"][:10] for d in buy_decisions],
                        y=[d.get("ticker", "") for d in buy_decisions],
                        mode="markers",
                        name="BUY",
                        marker=dict(color="#4CAF50", size=12, symbol="triangle-up"),
                    )
                )
            if sell_decisions:
                fig.add_trace(
                    go.Scatter(
                        x=[d["timestamp"][:10] for d in sell_decisions],
                        y=[d.get("ticker", "") for d in sell_decisions],
                        mode="markers",
                        name="SELL",
                        marker=dict(color="#F44336", size=12, symbol="triangle-down"),
                    )
                )
            if other_decisions:
                fig.add_trace(
                    go.Scatter(
                        x=[d["timestamp"][:10] for d in other_decisions],
                        y=[d.get("ticker", "") for d in other_decisions],
                        mode="markers",
                        name="Other",
                        marker=dict(color="#888888", size=8),
                    )
                )

            fig.update_layout(
                template="omaha_oracle",
                xaxis_title="Date",
                yaxis_title="Ticker",
                height=400,
            )
            st.plotly_chart(fig, width="stretch")
        else:
            st.info("No signals to display on timeline.")

    # ── Tier 3: Supplementary content ──
    if other_decisions:
        with st.expander(f"Other Signals ({len(other_decisions)})"):
            for d in other_decisions:
                _render_signal_card(d)
